// LENGTH CHECKER: CHECK HASH LENGTHS

// This is the "transaction data" I found in ganache, its too short...
const hash_to_check = "0xca89373f0000000000000000000000002736c5be05ee52a855080024be52894e00b24cdb0000000000000000000000000000000000000000000000000000000000000032";

console.log(hash_to_check.length); //logs 138

// I need to find the "full signed transaction hash" to recover the Alice's full public Key
// that we will use to encrypt so she can decrypt with her private key
// TODO - FIND "FULL SIGNED TRANSACTION HASHES" IN GANACHE SO I CAN RECOVER PUBLIC KEYS!
// (see the below medium article to see what I mean, 
// we want to find the 'signed transaction' hash thats at the top of the article)
// https://piyopiyo.medium.com/how-to-get-senders-ethereum-address-and-public-key-from-signed-transaction-44abe17a1791

const hash2 = "0xf86b808504a817c800825208942890228d4478e2c3b0ebf5a38479e3396c1d6074872386f26fc100008029a0520e5053c1b573d747f823a0b23d52e5a619298f46cd781d677d0e5e78fbc750a075be461137c2c2a5594beff76ecb11a215384c574a7e5b620dba5cc63b0a0f13";
console.log(hash2.length); // logs 220

// TEST3 SEE if the rawTransaction hash generated by generate_account.js is long as hash2
const hash3 = '0xf86c058504a817c800831e8480941f1def4d586cfbd8b46c8325b3853e6d5b04775887b1a2bc2ec500008026a0ffcccf2e6cc354abd508f8b420ec9b91d3b8eb6dea0f67db5932d895481356f3a01e1e307e78a6bc270eb63208b5f80548dc85a58177d6b6de00488be0c984a7dc';

console.log(hash3.length);

// TEST4 SEE if rawTxHash generated by 'signedTxToRawTransaction.js' has proper length
const hash4 = '0xf8711c8504a817c800836691b794fafbb1b11db14cf84fa6e5c60d0789ef0d99b74a887ce66c50e284000084d7bb99ba25a08d7d869106b635e6aa13cc6b7caefe914e4de7db1e122146edd276283fdc2e49a0367018baaf378c055df5ca09b7fdbd03b5a85fe393c0fea3be9461b10703ea4b';
console.log(hash4.length);

// random testing below
console.log('Dog' && true);